AWSTemplateFormatVersion: 2010-09-09

Description: craft-demo-base-app-env-shell

Resources:
  DataServicesElbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DataServicesElbSg
      VpcId: vpc-bc481fc5
      Tags:
      - Key: Name
        Value: DataServicesElbSg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5000
        ToPort: 5000
        SourceSecurityGroupId:
          Ref: WebServicesAppSg

  DataServicesAppSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DataServicesAppSg
      VpcId: vpc-bc481fc5
      Tags:
      - Key: Name
        Value: DataServicesAppSg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        SourceSecurityGroupId: sg-909338ee
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        SourceSecurityGroupId:
          Ref: DataServicesElbSg
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        SourceSecurityGroupId:
          Ref: DataServicesElbSg
      - IpProtocol: tcp
        FromPort: 5000
        ToPort: 5000
        SourceSecurityGroupId:
          Ref: DataServicesElbSg

  WebServicesAlbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: WebServicesAlbSg
      VpcId: vpc-bc481fc5
      Tags:
      - Key: Name
        Value: WebServicesAlbSg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
       
  WebServicesAppSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: WebServicesAppSg
      VpcId: vpc-bc481fc5
      Tags:
      - Key: Name
        Value: WebServicesAppSg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        SourceSecurityGroupId: sg-909338ee
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        SourceSecurityGroupId:
          Ref: WebServicesAlbSg
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        SourceSecurityGroupId:
          Ref: WebServicesAlbSg

  CraftDemoDbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: CraftDemoDbSg
      VpcId: vpc-bc481fc5
      Tags:
      - Key: Name
        Value: CraftDemoDbSg
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId: sg-909338ee
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId:
          Ref: DataServicesAppSg
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        SourceSecurityGroupId:
          Ref: WebServicesAppSg
          
Outputs:
  CloudFormationUpdateHack:
    Description: Allows us to perform no-op updates on a stack by changing only this value every time.
    Value: 20180407-172142
  WebServicesAppSgId:
    Export:
      Name: !Sub vpc-bc481fc5:craft-demo-base-app-WebServicesAppSg:id
    Value: !Ref WebServicesAppSg
  WebServicesAlbSgId:
    Export:
      Name: !Sub vpc-bc481fc5:craft-demo-base-app-WebServicesAlbSg:id
    Value: !Ref WebServicesAlbSg
  DataServicesElbSgId:
    Export:
      Name: !Sub vpc-bc481fc5:craft-demo-base-app-DataServicesElbSg:id
    Value: !Ref DataServicesElbSg
  DataServicesAppSgId:
    Export:
      Name: !Sub vpc-bc481fc5:craft-demo-base-app-DataServicesAppSg:id
    Value: !Ref DataServicesAppSg
  CraftDemoDbSgId:
    Export:
      Name: !Sub vpc-bc481fc5:craft-demo-base-app-CraftDemoDbSg:id
    Value: !Ref CraftDemoDbSg
